add: rollback, auto tagging workflow jobs

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -80,3 +80,49 @@ jobs:
           else
             exit 1
           fi
+
+  rollback / release:
+    runs-on: [ self-hosted, label-go ]
+    needs: [ checkout, deploy, test ]
+    if: ${{ always() && contains(needs.*.result, 'failure') }}
+    steps:
+      - name: Fetch Latest Release
+        id: fetch-latest
+        uses: thebritican/fetch-latest-release@v1.0.3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Checkout Latest Release source code
+        with:
+          fetch-depth: 0
+          ref: ${{ steps.latest.outputs.tag_name }}
+
+      - name: Build Docker containers
+        run: sh scripts/build-docker-compose.sh
+
+      - name: Check container running state
+        run: |
+          if [ $(docker ps --format "{{.Names}} {{.Status}}" | grep "Up" | wc -l) -ne 3 ]
+          then
+            echo "Build error while running docker-compose"
+            exit 1
+          else
+            echo "Deploy Complete"
+          fi
+
+  tagging / release:
+    runs-on: [ self-hosted, label-go ]
+    needs: [ checkout, deploy, test ]
+    if: ${{ always() && github.event.pull_request_merged == true && (needs.checkout.result == 'success' && needs.deploy.result == 'success' && needs.test.result == 'success) }}
+    steps:
+      - name: Extract version
+        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
+        id: extract-version
+
+      - name: Create Release with Tag
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.extract_version_name.outputs.version }}
+          release_name: ${{ steps.extract_version_name.outputs.version }}
